/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  safelist: [
    'min-h-screen',
    'flex',
    'items-center',
    'justify-center',
    'bg-gray-50',
    'dark:bg-gray-900',
    'w-full',
    'max-w-2xl',
    'p-6',
    'bg-white',
    'dark:bg-gray-800',
    'rounded-xl',
    'shadow-lg',
    'text-xl',
    'font-bold',
    'mb-3',
    'text-gray-800',
    'dark:text-white',
    'mb-4',
    'text-sm',
    'text-gray-600',
    'dark:text-gray-400',
    'min-h-[220px]',
    'p-5',
    'border-2',
    'border-gray-200',
    'dark:border-gray-700',
    'rounded-lg',
    'shadow-inner',
    'focus:border-blue-400',
    'dark:focus:border-blue-500',
    'focus:ring-2',
    'focus:ring-blue-200',
    'dark:focus:ring-blue-800',
    'hover:border-gray-300',
    'dark:hover:border-gray-600',
    'transition-all',
    'duration-200',
    'fixed',
    'px-4',
    'py-2',
    'bg-gradient-to-r',
    'from-indigo-500',
    'to-purple-600',
    'text-white',
    'font-medium',
    'hover:from-indigo-600',
    'hover:to-purple-700',
    'focus:ring-offset-2',
    'focus:ring-indigo-500',
    'transform',
    'hover:scale-105'
  ],
  theme: {
    extend: {},
  },
  plugins: [],
} 